language: objective-c
osx_image: xcode8
xcode_project: FastlineExample.xcodeproj
xcode_scheme: FastlineExample
bundler_args: --retry 5
branches:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem install bundle
  - bundle install && brew bundle
script:
  - bundle exec fastlane tests
