language: objective-c
osx_image: xcode8.0
xcode_project: FastlineExample.xcodeproj
xcode_scheme: FastlineExample
xcode_sdk: iphonesimulator9.0
branches:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem install bundle
  - bundle install && brew bundle
script:
  - bundle exec fastlane tests
