osx_image: xcode8.0
language: objective-c
branchs:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem install bundle
  - bundle install && brew bundle
script:
  - bundle exec fastlane tests
