default_platform :ios

lane :tests do
  scan(
    scheme: 'FastlineExample',
    devices: ["iPhone 5s", "iPhone 6", "iPhone 6s", "iPhone 6s Plus", "iPhone 7", "iPhone SE"],
    code_coverage: true
  )
end
